name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: ctlab/private-libraries
        TOKEN: ${{ secrets.DEPLOYSECRET }}
        path: 'lib'
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - run: mvn install:install-file -Dfile=lib/lib/cplex.jar -DgroupId=com.ibm -DartifactId=cplex -Dversion=12.7.1 -Dpackaging=jar
    - run: mvn install -DskipTests=true
    - run: java -Djava.library.path=lib/lib -cp lib/lib/cplex.jar:target/virgo-solver.jar ru.itmo.ctlab.virgo.Main -type sgmwcs -n examples/sgmwcs-1450/nodes -e examples/sgmwcs-1450/edges -s examples/sgmwcs-1450/signals
    - run: mvn -Djava.library.path=lib/lib test -B
    - run: mvn jacoco:report
    - uses: codecov/codecov-action@v2
      with:
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
